import { CheckCircle2, Edit3, MessageSquareText, ShieldCheck, Smartphone } from 'lucide-react';
import { useState } from 'react';
import { PageIntro, Panel } from './page-kit'; import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Switch } from '@/components/ui/switch'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { avatarStyle } from '@/lib/utils';
export { ContactsPage } from './contacts-workspace';
export { UsersPage } from './users-workspace';
export { BulkSmsPage } from './bulk-sms-workspace';
export function SettingsPage(){return <><PageIntro eyebrow="Workspace" title="Messaging settings" description="Set practical defaults for delivery, notifications, and patient communications."/><div className="page-pad grid gap-5 lg:grid-cols-[14rem_1fr]"><nav className="flex gap-1 overflow-x-auto pb-1 lg:block lg:space-y-1 lg:overflow-visible"><Button variant="settingActive" className="w-auto shrink-0 justify-start lg:w-full"><MessageSquareText/>Messaging</Button><Button variant="ghost" className="w-auto shrink-0 justify-start lg:w-full"><BellIcon/>Notifications</Button><Button variant="ghost" className="w-auto shrink-0 justify-start lg:w-full"><ShieldCheck/>Security</Button></nav><Panel className="divide-y divide-border"><Setting title="Delivery receipts" desc="Show sent, delivered, and read status in conversations."/><Setting title="Desktop notifications" desc="Notify you when a new message arrives."/><Setting title="Appointment templates" desc="Suggest approved templates while composing."/><div className="p-4 sm:p-5"><label className="field-label">Default sender number</label><Select defaultValue="office"><SelectTrigger className="form-select mt-2 max-w-md"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="office">+1 (909) 671-0123 · Main office</SelectItem></SelectContent></Select><div className="mt-5"><Button className="w-full sm:w-auto">Save changes</Button></div></div></Panel></div></>}
function BellIcon(){return <Smartphone/>}
function Setting({title,desc}:{title:string;desc:string}){const [on,setOn]=useState(true);return <div className="flex items-center gap-3 p-4 sm:gap-4 sm:p-5"><div className="min-w-0 flex-1"><strong className="text-sm">{title}</strong><p className="mt-1 text-xs text-muted-foreground">{desc}</p></div><Switch checked={on} onCheckedChange={setOn}/></div>}
export function ProfilePage(){return <><PageIntro eyebrow="Account" title="Your profile" description="Keep your identity and communication preferences current."/><div className="page-pad"><Panel className="mx-auto max-w-3xl overflow-hidden"><div className="profile-band"/><div className="p-5 sm:p-8"><div className="-mt-18 mb-7 flex flex-col items-start gap-4 sm:flex-row sm:items-end"><div className="profile-avatar" style={avatarStyle('Imran Shabbir')}>IS</div><div className="pb-1"><h3 className="font-display text-xl font-semibold">Imran Shabbir</h3><p className="text-sm text-muted-foreground">Workspace administrator</p></div><Button variant="outline" className="w-full sm:ml-auto sm:w-auto"><Edit3/>Change photo</Button></div><div className="form-grid"><label><span>First name</span><Input defaultValue="Imran"/></label><label><span>Last name</span><Input defaultValue="Shabbir"/></label><label><span>Email address</span><Input defaultValue="imran@example.com"/></label><label><span>Phone number</span><Input defaultValue="+1 (909) 671-0123"/></label><label className="sm:col-span-2"><span>Role</span><Input value="Administrator" disabled/></label></div><div className="mt-6 flex justify-end"><Button className="w-full sm:w-auto"><CheckCircle2/>Save profile</Button></div></div></Panel></div></>}