import { Bookmark, CheckCheck, ChevronLeft, MoreHorizontal, Paperclip, Phone, Plus, Search, Send, Trash2, UserRound, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { initialConversations, type Conversation } from '@/data/demo';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { cn } from '@/lib/utils';

type Tab='recent'|'bookmarked'|'unread';
export function SmsWorkspace(){
 const [items,setItems]=useState(initialConversations); const [selected,setSelected]=useState('1'); const [query,setQuery]=useState(''); const [tab,setTab]=useState<Tab>('recent'); const [draft,setDraft]=useState(''); const [creating,setCreating]=useState(false); const [recipient,setRecipient]=useState('');
 const active=items.find(x=>x.id===selected); const filtered=useMemo(()=>items.filter(x=>(tab==='bookmarked'?x.bookmarked:tab==='unread'?x.unread>0:true)&&`${x.name} ${x.phone} ${x.preview}`.toLowerCase().includes(query.toLowerCase())),[items,query,tab]);
 const select=(id:string)=>{setSelected(id);setItems(v=>v.map(x=>x.id===id?{...x,unread:0}:x));};
 const send=()=>{if(!draft.trim()||!active)return;setItems(v=>v.map(x=>x.id===active.id?{...x,preview:draft,time:'Now',messages:[...x.messages,{id:crypto.randomUUID(),body:draft,time:'Now',outgoing:true}]}:x));setDraft('');};
 const create=()=>{if(!recipient.trim())return; const id=crypto.randomUUID();setItems(v=>[{id,name:recipient,phone:recipient,source:'New contact',initials:recipient.slice(0,2).toUpperCase(),preview:'New conversation',time:'Now',unread:0,bookmarked:false,messages:[]},...v]);setSelected(id);setCreating(false);setRecipient('');};
 const remove=()=>{if(!active)return;setItems(v=>v.filter(x=>x.id!==active.id));setSelected('');};
 return <div className="h-[calc(100vh-4.5rem)] overflow-hidden bg-workspace md:grid md:grid-cols-[minmax(20rem,24rem)_1fr]">
  <section className={cn('flex h-full min-w-0 flex-col border-r border-border bg-surface',active?'hidden md:flex':'flex')}>
   <div className="space-y-4 border-b border-border p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Inbox</p><p className="text-xs text-muted-foreground">{items.reduce((s,x)=>s+x.unread,0)} unread messages</p></div><Button size="sm" onClick={()=>setCreating(true)}><Plus/>New</Button></div>
   <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" size={16}/><Input aria-label="Search conversations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations" className="h-10 bg-muted/50 pl-9"/></div>
   <div className="flex gap-1 rounded-lg bg-muted p-1">{(['recent','bookmarked','unread'] as Tab[]).map(t=><Button key={t} variant={tab===t?'tabActive':'tab'} size="sm" onClick={()=>setTab(t)} className="flex-1 capitalize">{t}</Button>)}</div></div>
   {creating&&<div className="border-b border-border bg-accent/40 p-4"><div className="mb-2 flex items-center justify-between"><strong className="text-sm">Start a conversation</strong><Button variant="ghost" size="iconSm" onClick={()=>setCreating(false)} aria-label="Close"><X/></Button></div><div className="flex gap-2"><Input autoFocus value={recipient} onChange={e=>setRecipient(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')create()}} placeholder="Name or phone number"/><Button size="icon" onClick={create} aria-label="Create conversation"><Send/></Button></div></div>}
   <div className="min-h-0 flex-1 overflow-y-auto p-2">{filtered.length?filtered.map(c=><ConversationRow key={c.id} item={c} active={c.id===selected} onSelect={()=>select(c.id)} onBookmark={()=>setItems(v=>v.map(x=>x.id===c.id?{...x,bookmarked:!x.bookmarked}:x))}/>):<div className="grid h-48 place-items-center text-center"><div><Search className="mx-auto mb-2 text-muted-foreground"/><p className="text-sm font-medium">No conversations found</p><p className="text-xs text-muted-foreground">Try another search or filter.</p></div></div>}</div>
  </section>
  {active?<section className="flex h-full min-w-0 flex-col bg-workspace"><header className="flex h-18 shrink-0 items-center gap-3 border-b border-border bg-surface px-4"><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setSelected('')} aria-label="Back"><ChevronLeft/></Button><div className="avatar-sm">{active.initials}</div><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{active.name}</h3><p className="text-xs text-muted-foreground">{active.phone} · <span className="text-success">SMS available</span></p></div><div className="ml-auto flex gap-1"><Button variant="ghost" size="icon" aria-label="Call"><Phone/></Button><Button variant="ghost" size="icon" onClick={()=>setItems(v=>v.map(x=>x.id===active.id?{...x,bookmarked:!x.bookmarked}:x))} aria-label="Bookmark"><Bookmark className={active.bookmarked?'fill-primary text-primary':''}/></Button><Button variant="ghost" size="icon" onClick={remove} aria-label="Delete"><Trash2/></Button><Button variant="ghost" size="icon" aria-label="More options"><MoreHorizontal/></Button></div></header>
   <div className="min-h-0 flex-1 overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-3xl"><div className="mb-6 flex items-center gap-3 text-xs text-muted-foreground before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">Today</div>{active.messages.length?active.messages.map(m=><div key={m.id} className={cn('mb-5 flex',m.outgoing?'justify-end':'justify-start')}><div className={cn('max-w-[84%] sm:max-w-[70%]',m.outgoing?'text-right':'')}><div className={cn('message-bubble',m.outgoing?'message-out':'message-in')}>{m.body}</div><div className={cn('mt-1.5 flex items-center gap-1 text-xs text-muted-foreground',m.outgoing&&'justify-end')}>{m.time}{m.outgoing&&<CheckCheck size={14} className="text-primary"/>}</div></div></div>):<div className="grid h-80 place-items-center text-center"><div><div className="avatar-lg mx-auto mb-3"><UserRound/></div><h3 className="font-display font-semibold">New conversation</h3><p className="mt-1 text-sm text-muted-foreground">Send the first message to {active.name}.</p></div></div>}</div></div>
   <div className="shrink-0 border-t border-border bg-surface p-3 sm:p-4"><div className="mx-auto flex max-w-3xl items-end gap-2 rounded-lg border border-input bg-background p-2 shadow-soft focus-within:ring-2 focus-within:ring-ring/30"><Button variant="ghost" size="icon" aria-label="Attach file"><Paperclip/></Button><textarea aria-label="Message" value={draft} onChange={e=>setDraft(e.target.value.slice(0,320))} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={1} placeholder="Type a message…" className="min-h-9 max-h-28 flex-1 resize-none bg-transparent px-1 py-2 text-sm outline-none placeholder:text-muted-foreground"/><span className="hidden pb-2 text-xs text-muted-foreground sm:block">{draft.length}/320</span><Button size="icon" onClick={send} disabled={!draft.trim()} aria-label="Send message"><Send/></Button></div></div>
  </section>:<section className="hidden h-full place-items-center bg-workspace md:grid"><div className="text-center"><div className="avatar-lg mx-auto mb-4"><MessageCircleIcon/></div><h3 className="font-display text-lg font-semibold">Your conversations</h3><p className="mt-1 text-sm text-muted-foreground">Select a thread to read and reply.</p></div></section>}
 </div>
}
function MessageCircleIcon(){return <Send/>}
function ConversationRow({item,active,onSelect,onBookmark}:{item:Conversation;active:boolean;onSelect:()=>void;onBookmark:()=>void}){return <div className={cn('group mb-1 flex cursor-pointer gap-3 rounded-lg border p-3 transition-all',active?'border-primary/25 bg-accent shadow-soft':'border-transparent hover:bg-muted/70')} onClick={onSelect}><div className="avatar-sm">{item.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-sm">{item.name}</strong><span className="ml-auto shrink-0 text-xs text-muted-foreground">{item.time}</span></div><div className="mt-1 flex items-center gap-2"><span className="truncate text-xs text-muted-foreground">{item.preview}</span>{item.unread>0&&<span className="unread-count">{item.unread}</span>}</div><div className="mt-2 flex items-center"><span className="source-tag">{item.source}</span><Button variant="ghost" size="iconSm" className="ml-auto" onClick={e=>{e.stopPropagation();onBookmark()}} aria-label="Toggle bookmark"><Bookmark className={item.bookmarked?'fill-primary text-primary':''}/></Button></div></div></div>}
