import { Bookmark, CheckCheck, ChevronLeft, FileText, Image as ImageIcon, MoreHorizontal, Paperclip, Plus, Search, Send, Smile, Trash2, UserRound, X } from 'lucide-react';
import { useMemo, useRef, useState, type ChangeEvent } from 'react';
import { contacts, initialConversations, type Conversation } from '@/data/demo';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'; import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'; import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { avatarStyle, cn } from '@/lib/utils';

const emojis = ['😀','😁','😂','🤣','😊','😇','😉','😍','😘','😋','😎','🤩','🥳','🥰','🤗','🤔','🙄','😬','😳','😴','😢','😭','😤','😡','🤯','👍','👎','👏','🙏','💪','✌️','👌','🤝','👋','🙌','❤️','🧡','💛','💚','💙','💜','🖤','🤍','💔','🔥','✨','⭐','🎉','💯','✅','❌','💬','📷','📎','📱','🏠'];

type Tab='recent'|'bookmarked'|'unread';
type SearchBy='phone'|'name';
type NewBy='phone'|'company'|'name';
type DirectoryHit={key:string;name:string;phone:string;company:string;chatId?:string};
const digits=(value:string)=>value.replace(/\D/g,'');
export function SmsWorkspace(){
 const [items,setItems]=useState(initialConversations); const [selected,setSelected]=useState('1'); const [query,setQuery]=useState(''); const [searchBy,setSearchBy]=useState<SearchBy>('phone'); const [tab,setTab]=useState<Tab>('recent'); const [draft,setDraft]=useState(''); const [creating,setCreating]=useState(false); const [newQuery,setNewQuery]=useState(''); const [newBy,setNewBy]=useState<NewBy>('phone'); const [picked,setPicked]=useState<string>(''); const [attachments,setAttachments]=useState<File[]>([]); const [attachOpen,setAttachOpen]=useState(false); const [attachView,setAttachView]=useState<'menu'|'emoji'>('menu'); const photoRef=useRef<HTMLInputElement>(null); const fileRef=useRef<HTMLInputElement>(null);
 const active=items.find(x=>x.id===selected); const filtered=useMemo(()=>items.filter(x=>{const tabOk=tab==='bookmarked'?x.bookmarked:tab==='unread'?x.unread>0:true; if(!tabOk) return false; const q=query.trim().toLowerCase(); if(!q) return true; return searchBy==='phone'?(digits(q)?digits(x.phone).includes(digits(q)):x.phone.toLowerCase().includes(q)):x.name.toLowerCase().includes(q);}),[items,query,searchBy,tab]);
 const directory=useMemo(()=>{const rows:DirectoryHit[]=items.map(x=>({key:x.id,name:x.name,phone:x.phone,company:x.source,chatId:x.id})); for(const [name,company,phone] of contacts){ if(rows.some(r=>digits(r.phone)===digits(phone)||r.name===name)) continue; rows.push({key:phone,name,phone,company}); } return rows;},[items]);
 const newHits=useMemo(()=>{const q=newQuery.trim().toLowerCase(); if(!q) return directory; return directory.filter(r=>newBy==='phone'?(digits(q)?digits(r.phone).includes(digits(q)):r.phone.toLowerCase().includes(q)):newBy==='company'?r.company.toLowerCase().includes(q):r.name.toLowerCase().includes(q));},[directory,newQuery,newBy]);
 const select=(id:string)=>{setSelected(id);setItems(v=>v.map(x=>x.id===id?{...x,unread:0}:x));};
 const send=()=>{if((!draft.trim()&&!attachments.length)||!active)return; const extra=attachments.map(f=>f.type.startsWith('image/')?`📷 ${f.name}`:`📎 ${f.name}`).join(' '); const body=[draft.trim(),extra].filter(Boolean).join(' '); setItems(v=>v.map(x=>x.id===active.id?{...x,preview:body,time:'Now',messages:[...x.messages,{id:crypto.randomUUID(),body,time:'Now',outgoing:true}]}:x));setDraft('');setAttachments([]);}; const addFiles=(e:ChangeEvent<HTMLInputElement>)=>{const next=Array.from(e.target.files??[]); if(next.length) setAttachments(v=>[...v,...next]); e.target.value='';}; const addEmoji=(emoji:string)=>setDraft(v=>(v+emoji).slice(0,320));
 const closeNew=()=>{setCreating(false);setNewQuery('');setNewBy('phone');setPicked('');};
 const openChat=(hit:DirectoryHit)=>{if(hit.chatId){select(hit.chatId);closeNew();return;} const id=crypto.randomUUID(); setItems(v=>[{id,name:hit.name,phone:hit.phone,source:hit.company,initials:hit.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase(),preview:'New conversation',time:'Now',unread:0,bookmarked:false,messages:[]},...v]); setSelected(id); closeNew();};
 const startNew=()=>{const hit=newHits.find(x=>x.key===picked)??(newHits.length===1?newHits[0]:undefined); if(hit){openChat(hit);return;} if(!newQuery.trim())return; const id=crypto.randomUUID(); const label=newQuery.trim(); setItems(v=>[{id,name:label,phone:label,source:'New contact',initials:label.slice(0,2).toUpperCase(),preview:'New conversation',time:'Now',unread:0,bookmarked:false,messages:[]},...v]); setSelected(id); closeNew();};
 const remove=()=>{if(!active)return;setItems(v=>v.filter(x=>x.id!==active.id));setSelected('');};
 return <div className="flex h-full min-h-0 overflow-hidden bg-workspace md:grid md:grid-cols-[minmax(18rem,24rem)_minmax(0,1fr)] md:grid-rows-[minmax(0,1fr)] xl:grid-cols-[minmax(26rem,32rem)_minmax(0,1fr)]">
   <section className={cn('flex h-full min-h-0 min-w-0 flex-col border-r border-border bg-surface',active?'hidden md:flex':'flex')}>
   <div className="space-y-4 border-b border-border p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Inbox</p><p className="text-xs text-muted-foreground">{items.reduce((s,x)=>s+x.unread,0)} unread messages</p></div><Button size="sm" className="rounded-full" onClick={()=>{setPicked('');setNewQuery('');setNewBy('phone');setCreating(true);}}><Plus/>New</Button></div>
   <div className="flex flex-wrap items-center gap-2"><Input aria-label={searchBy==='phone'?'Search by phone number':'Search by client name'} value={query} onChange={e=>setQuery(e.target.value)} placeholder={searchBy==='phone'?'Search phone number':'Search client name'} className="h-9 min-w-0 flex-[1.6] bg-muted/50"/><Select value={searchBy} onValueChange={v=>setSearchBy(v as SearchBy)}><SelectTrigger className="h-9 w-[9.75rem] max-w-full shrink-0 bg-muted/50" aria-label="Search by"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="phone">Phone Number</SelectItem><SelectItem value="name">Client Name</SelectItem></SelectContent></Select><Button type="button" size="icon" variant="ghost" aria-label="Search"><Search size={16}/></Button></div>
   <div className="flex gap-1 rounded-lg bg-muted p-1">{(['recent','bookmarked','unread'] as Tab[]).map(t=><Button key={t} variant={tab===t?'tabActive':'tab'} size="sm" onClick={()=>setTab(t)} className="flex-1 capitalize">{t}</Button>)}</div></div>
   <Dialog open={creating} onOpenChange={(open)=>{if(open) setCreating(true); else closeNew();}}><DialogContent className="new-message-modal"><DialogHeader><DialogTitle>New Message</DialogTitle><DialogDescription>Search an existing contact, then start the chat.</DialogDescription></DialogHeader><div><p className="mb-2 text-xs font-semibold text-muted-foreground">To:</p><div className="flex flex-wrap items-center gap-2"><Input autoFocus value={newQuery} onChange={e=>setNewQuery(e.target.value)} placeholder={newBy==='phone'?'Search phone number':newBy==='company'?'Search company name':'Search client name'} className="h-9 min-w-0 flex-1 rounded-full bg-muted/50" onKeyDown={e=>{if(e.key==='Enter')startNew()}}/><Select value={newBy} onValueChange={v=>setNewBy(v as NewBy)}><SelectTrigger className="h-9 w-[10.5rem] max-w-full shrink-0 rounded-full bg-muted/50" aria-label="Search new message by"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="phone">Phone Number</SelectItem><SelectItem value="company">Company Name</SelectItem><SelectItem value="name">Client Name</SelectItem></SelectContent></Select></div><div className="mt-3 max-h-56 overflow-y-auto">{newHits.length?newHits.map(hit=><button key={hit.key} type="button" className={cn('new-message-hit',picked===hit.key&&'new-message-hit-active')} onClick={()=>openChat(hit)}><span className="avatar-sm" style={avatarStyle(hit.name)}>{hit.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{hit.name}</strong><small className={cn('block truncate text-xs',picked===hit.key?'text-white/80':'text-muted-foreground')}>{hit.phone} · {hit.company}</small></span></button>):<p className="px-2 py-6 text-center text-sm text-muted-foreground">No matching contacts.</p>}</div></div><DialogFooter><Button type="button" variant="outline" className="rounded-full" onClick={closeNew}>Close</Button><Button type="button" className="rounded-full" onClick={startNew}>Start new Chat</Button></DialogFooter></DialogContent></Dialog>
   <div className="min-h-0 flex-1 overflow-y-auto p-2">{filtered.length?filtered.map(c=><ConversationRow key={c.id} item={c} active={c.id===selected} onSelect={()=>select(c.id)} onBookmark={()=>setItems(v=>v.map(x=>x.id===c.id?{...x,bookmarked:!x.bookmarked}:x))}/>):<div className="grid h-48 place-items-center text-center"><div><Search className="mx-auto mb-2 text-muted-foreground"/><p className="text-sm font-medium">No conversations found</p><p className="text-xs text-muted-foreground">Try another search or filter.</p></div></div>}</div>
  </section>
  {active?<section className="flex h-full min-h-0 min-w-0 flex-col bg-workspace"><header className="flex h-18 shrink-0 items-center gap-3 border-b border-border bg-surface px-4"><Button variant="ghost" size="icon" className="md:hidden" onClick={()=>setSelected('')} aria-label="Back"><ChevronLeft/></Button><div className="avatar-sm" style={avatarStyle(active.name)}>{active.initials}</div><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{active.name}</h3><p className="text-xs text-muted-foreground">{active.phone} · <span className="text-success">SMS available</span></p></div><div className="ml-auto flex gap-1"><Button variant="ghost" size="icon" onClick={()=>setItems(v=>v.map(x=>x.id===active.id?{...x,bookmarked:!x.bookmarked}:x))} aria-label="Bookmark"><Bookmark className={active.bookmarked?'fill-primary text-primary':''}/></Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label="More options"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={remove}><Trash2/> Delete conversation</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></header>
   <div className="min-h-0 flex-1 overflow-y-auto px-4 py-6 sm:px-8"><div className="mx-auto max-w-3xl"><div className="mb-6 flex items-center gap-3 text-xs text-muted-foreground before:h-px before:flex-1 before:bg-border after:h-px after:flex-1 after:bg-border">Today</div>{active.messages.length?active.messages.map(m=><div key={m.id} className={cn('mb-5 flex',m.outgoing?'justify-end':'justify-start')}><div className={cn('max-w-[84%] sm:max-w-[70%]',m.outgoing?'text-right':'')}><div className={cn('message-bubble',m.outgoing?'message-out':'message-in')}>{m.body}</div><div className={cn('mt-1.5 flex items-center gap-1 text-xs text-muted-foreground',m.outgoing&&'justify-end')}>{m.time}{m.outgoing&&<CheckCheck size={14} className="text-primary"/>}</div></div></div>):<div className="grid h-80 place-items-center text-center"><div><div className="avatar-lg mx-auto mb-3"><UserRound/></div><h3 className="font-display font-semibold">New conversation</h3><p className="mt-1 text-sm text-muted-foreground">Send the first message to {active.name}.</p></div></div>}</div></div>
   <div className="shrink-0 border-t border-border bg-surface px-3 py-3 sm:px-5"><div className="mx-auto w-[96%]"><input ref={photoRef} type="file" accept="image/*" multiple className="hidden" onChange={addFiles}/><input ref={fileRef} type="file" multiple className="hidden" onChange={addFiles}/>{attachments.length>0&&<div className="mb-2 flex flex-wrap gap-1.5">{attachments.map((f,i)=><span key={`${f.name}-${i}`} className="attach-chip"><span className="truncate">{f.name}</span><button type="button" aria-label={`Remove ${f.name}`} onClick={()=>setAttachments(v=>v.filter((_,idx)=>idx!==i))}><X size={12}/></button></span>)}</div>}<div className="flex items-end gap-2 rounded-full border border-input bg-background px-2 py-1.5 shadow-soft focus-within:ring-2 focus-within:ring-ring/30"><Popover open={attachOpen} onOpenChange={(next)=>{setAttachOpen(next); if(next) setAttachView('menu');}}><PopoverTrigger asChild><Button variant="ghost" size="icon" aria-label="Attach"><Paperclip/></Button></PopoverTrigger><PopoverContent side="top" align="start" sideOffset={10} className="attach-sheet p-0">{attachView==='menu'?<div className="flex justify-around px-2 py-1.5">{[{label:'Photos',icon:ImageIcon,style:'attach-orb-photo',onClick:()=>{setAttachOpen(false);photoRef.current?.click()}},{label:'Files',icon:FileText,style:'attach-orb-file',onClick:()=>{setAttachOpen(false);fileRef.current?.click()}},{label:'Emoji',icon:Smile,style:'attach-orb-emoji',onClick:()=>setAttachView('emoji')}].map(item=><button key={item.label} type="button" className="flex flex-col items-center gap-1" onClick={item.onClick}><span className={cn('attach-orb',item.style)}><item.icon size={13}/></span><span className="text-[0.62rem] font-semibold text-foreground">{item.label}</span></button>)}</div>:<div className="p-3"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold text-foreground">Emoji</p><button type="button" className="text-xs font-semibold text-primary" onClick={()=>setAttachView('menu')}>Back</button></div><div className="emoji-grid">{emojis.map(e=><button key={e} type="button" className="grid h-8 place-items-center rounded-md hover:bg-muted" onClick={()=>addEmoji(e)}><span className="native-emoji">{e}</span></button>)}</div></div>}</PopoverContent></Popover><textarea aria-label="Message" value={draft} onChange={e=>setDraft(e.target.value.slice(0,320))} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={1} placeholder="Type a message…" className="min-h-9 max-h-28 flex-1 resize-none bg-transparent px-1 py-2 text-sm outline-none placeholder:text-muted-foreground"/><span className="hidden pb-2 text-xs text-muted-foreground sm:block">{draft.length}/320</span><Button size="icon" className="rounded-full" onClick={send} disabled={!draft.trim()&&!attachments.length} aria-label="Send message"><Send/></Button></div></div></div>
  </section>:<section className="hidden h-full place-items-center bg-workspace md:grid"><div className="text-center"><div className="avatar-lg mx-auto mb-4"><MessageCircleIcon/></div><h3 className="font-display text-lg font-semibold">Your conversations</h3><p className="mt-1 text-sm text-muted-foreground">Select a thread to read and reply.</p></div></section>}
 </div>
}
function MessageCircleIcon(){return <Send/>}
function ConversationRow({item,active,onSelect,onBookmark}:{item:Conversation;active:boolean;onSelect:()=>void;onBookmark:()=>void}){return <div className={cn('group mb-1 flex cursor-pointer gap-3 rounded-lg border p-3 transition-all',active?'border-primary/25 bg-accent shadow-soft':'border-transparent hover:bg-muted/70')} onClick={onSelect}><div className="avatar-sm" style={avatarStyle(item.name)}>{item.initials}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><strong className="truncate text-sm">{item.name}</strong><span className="truncate text-xs text-muted-foreground">{item.phone}</span><span className="ml-auto shrink-0 text-xs text-muted-foreground">{item.time}</span><Button variant="ghost" size="iconSm" onClick={e=>{e.stopPropagation();onBookmark()}} aria-label="Toggle bookmark"><Bookmark className={item.bookmarked?'fill-primary text-primary':''}/></Button></div><div className="mt-1 flex items-center gap-2"><span className="truncate text-xs text-muted-foreground">{item.preview}</span>{item.unread>0&&<span className="unread-count">{item.unread}</span>}</div></div></div>}
