/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BulkSmsRouteImport } from './routes/bulk-sms'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkSmsRoute = BulkSmsRouteImport.update({
  id: '/bulk-sms',
  path: '/bulk-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk-sms': typeof BulkSmsRoute
  '/contacts': typeof ContactsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk-sms': typeof BulkSmsRoute
  '/contacts': typeof ContactsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk-sms': typeof BulkSmsRoute
  '/contacts': typeof ContactsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk-sms'
    | '/contacts'
    | '/profile'
    | '/settings'
    | '/sms'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk-sms'
    | '/contacts'
    | '/profile'
    | '/settings'
    | '/sms'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/bulk-sms'
    | '/contacts'
    | '/profile'
    | '/settings'
    | '/sms'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkSmsRoute: typeof BulkSmsRoute
  ContactsRoute: typeof ContactsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SmsRoute: typeof SmsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-sms': {
      id: '/bulk-sms'
      path: '/bulk-sms'
      fullPath: '/bulk-sms'
      preLoaderRoute: typeof BulkSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkSmsRoute: BulkSmsRoute,
  ContactsRoute: ContactsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SmsRoute: SmsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
